name: Deploy Smart Contract Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your source files are on a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # The output directory of your documentation
